package drools;

import app.entities.Patient;
import entities.Diagnosis;
import entities.Symptom;
import entities.LeucemiaType;
import entities.Sex;
import java.util.List;

//REGLAS ETIOLÓGICAS DEL PACIENTE:
rule "Regla: Riesgo etiológico para LMC"
    salience 10
    when
        $patient: Patient($id: id)
        $d: Diagnosis(patientId == $id, type == LeucemiaType.MC)
    then
        if($patient.getAge()<10 || ($patient.getAge()>=18 && $patient.getAge()<60)){
            $d.incrementRiskFactorIndex(2);
        }
        if($patient.isGenFiladelfia()){
            $d.incrementRiskFactorIndex(5);
        }
        if($patient.isRadOQuimicos()){
            $d.incrementRiskFactorIndex(1);
        }
        if($patient.isTransplanteMO()){
            $d.incrementRiskFactorIndex(2);
        }
        if($patient.isFarmacosQuimio()){
            $d.incrementRiskFactorIndex(2);
        }
        if($patient.isAntecedentesFamiliares()){
            $d.incrementRiskFactorIndex(1);
        }
end

rule "Regla: Riesgo etiológico para LMA"
    salience 10
    when
        $patient: Patient($id: id)
        $d: Diagnosis(patientId == $id, type == LeucemiaType.MA)
    then
        if($patient.getAge()>=10 && $patient.getAge()<18){
            $d.incrementRiskFactorIndex(2);
        }
        if($patient.getSex().equals(Sex.MALE)){
            $d.incrementRiskFactorIndex(3);
        }
        if($patient.isTrastornosSang()){
            $d.incrementRiskFactorIndex(2);
        }
        if($patient.isRadOQuimicos()){
            $d.incrementRiskFactorIndex(1);
        }
        if($patient.isTransplanteMO()){
            $d.incrementRiskFactorIndex(2);
        }
        if($patient.isFarmacosQuimio()){
            $d.incrementRiskFactorIndex(2);
        }
        if($patient.isAntecedentesFamiliares()){
            $d.incrementRiskFactorIndex(1);
        }
end

rule "Regla: Riesgo etiológico para LLC"
    salience 10
    when
        $patient: Patient($id: id)
        $d: Diagnosis(patientId == $id, type == LeucemiaType.LC)
    then
        if($patient.getAge()>=60){
            $d.incrementRiskFactorIndex(2);
        }
        if($patient.getSex().equals(Sex.MALE)){
            $d.incrementRiskFactorIndex(3);
        }
        if($patient.isRazaBlanca()){
            $d.incrementRiskFactorIndex(2);
        }
        if($patient.isTransplanteMO()){
            $d.incrementRiskFactorIndex(2);
        }
        if($patient.isFarmacosQuimio()){
            $d.incrementRiskFactorIndex(2);
        }
        if($patient.isAntecedentesFamiliares()){
            $d.incrementRiskFactorIndex(1);
        }
end

rule "Regla: Riesgo etiológico para LLA"
    salience 10
    when
        $patient: Patient($id: id)
        $d: Diagnosis(patientId == $id, type == LeucemiaType.LA)
    then
        if($patient.getAge()<18){
            $d.incrementRiskFactorIndex(2);
        }
        if($patient.isTrastornosGeneticos()){
            $d.incrementRiskFactorIndex(3);
        }
        if($patient.isHermanosLeucemia()){
            $d.incrementRiskFactorIndex(3);
        }
        if($patient.isTransplanteMO()){
            $d.incrementRiskFactorIndex(2);
        }
        if($patient.isFarmacosQuimio()){
            $d.incrementRiskFactorIndex(2);
        }
        if($patient.isAntecedentesFamiliares()){
            $d.incrementRiskFactorIndex(1);
        }
end


//REGLAS SINTOMÁTICAS DEL PACIENTE:
rule "Probando síntoma fiebre"
    salience 5
    when
        $patient: Patient($id: id)
        $symptom: Symptom(patientId == $id, name == "Fiebre", treated == false)
        $dLMC: Diagnosis(patientId == $id, type == LeucemiaType.MC)
        $dLMA: Diagnosis(patientId == $id, type == LeucemiaType.MA)
        $dLLC: Diagnosis(patientId == $id, type == LeucemiaType.LC)
        $dLLA: Diagnosis(patientId == $id, type == LeucemiaType.LA)
    then
        modify($symptom) {setTreated(true)};
        $dLMC.addSymptom($symptom);
        $dLMA.addSymptom($symptom);
        $dLLC.addSymptom($symptom);
        $dLLA.addSymptom($symptom);
end

rule "Probando síntoma fatiga"
    salience 5
    when
        $patient: Patient($id: id)
        $symptom: Symptom(patientId == $id, name == "Fatiga", treated == false)
        $dLMC: Diagnosis(patientId == $id, type == LeucemiaType.MC)
        $dLMA: Diagnosis(patientId == $id, type == LeucemiaType.MA)
        $dLLC: Diagnosis(patientId == $id, type == LeucemiaType.LC)
        $dLLA: Diagnosis(patientId == $id, type == LeucemiaType.LA)
    then
        modify($symptom) {setTreated(true)};
        $dLMC.addSymptom($symptom);
        $dLMA.addSymptom($symptom);
        $dLLC.addSymptom($symptom);
        $dLLA.addSymptom($symptom);
end

rule "Probando síntoma debilidad"
    salience 5
    when
        $patient: Patient($id: id)
        $symptom: Symptom(patientId == $id, name == "Debilidad", treated == false)
        $dLMC: Diagnosis(patientId == $id, type == LeucemiaType.MC)
        $dLLA: Diagnosis(patientId == $id, type == LeucemiaType.LA)
    then
        modify($symptom) {setTreated(true)};
        $dLMC.addSymptom($symptom);
        $dLLA.addSymptom($symptom);
end

rule "Probando síntoma palidez"
    salience 5
    when
        $patient: Patient($id: id)
        $symptom: Symptom(patientId == $id, name == "Palidez", treated == false)
        $dLMA: Diagnosis(patientId == $id, type == LeucemiaType.MA)
        $dLLA: Diagnosis(patientId == $id, type == LeucemiaType.LA)
    then
        modify($symptom) {setTreated(true)};
        $dLMA.addSymptom($symptom);
        $dLLA.addSymptom($symptom);
end

rule "Probando síntoma dificultad para respirar"
    salience 5
    when
        $patient: Patient($id: id)
        $symptom: Symptom(patientId == $id, name == "Dificultad respiratoria", treated == false)
        $dLMA: Diagnosis(patientId == $id, type == LeucemiaType.MA)
    then
        modify($symptom) {setTreated(true)};
        $dLMA.addSymptom($symptom);
end

rule "Probando síntoma infecciones recurrentes"
    salience 5
    when
        $patient: Patient($id: id)
        $symptom: Symptom(patientId == $id, name == "Infecciones recurrentes", treated == false)
        $dLLC: Diagnosis(patientId == $id, type == LeucemiaType.LC)
    then
        modify($symptom) {setTreated(true)};
        $dLLC.addSymptom($symptom);
end

rule "Probando síntoma tendencia a hematomas"
    salience 5
    when
        $patient: Patient($id: id)
        $symptom: Symptom(patientId == $id, name == "Propenso a hematomas", treated == false)
        $dLMC: Diagnosis(patientId == $id, type == LeucemiaType.MC)
        $dLMA: Diagnosis(patientId == $id, type == LeucemiaType.MA)
        $dLLA: Diagnosis(patientId == $id, type == LeucemiaType.LA)
    then
        modify($symptom) {setTreated(true)};
        $dLMC.addSymptom($symptom);
        $dLMA.addSymptom($symptom);
        $dLLA.addSymptom($symptom);
end

rule "Probando síntoma pequeñas manchas en la piel (petequias)"
    salience 5
    when
        $patient: Patient($id: id)
        $symptom: Symptom(patientId == $id, name == "Petequias", treated == false)
        $dLMC: Diagnosis(patientId == $id, type == LeucemiaType.MC)
        $dLLA: Diagnosis(patientId == $id, type == LeucemiaType.LA)
    then
        modify($symptom) {setTreated(true)};
        $dLMC.addSymptom($symptom);
        $dLLA.addSymptom($symptom);
end

rule "Probando síntoma sudoracion excesiva nocturna"
    salience 5
    when
        $patient: Patient($id: id)
        $symptom: Symptom(patientId == $id, name == "Sudores nocturnos", treated == false)
        $dLMC: Diagnosis(patientId == $id, type == LeucemiaType.MC)
    then
        modify($symptom) {setTreated(true)};
        $dLMC.addSymptom($symptom);
end

rule "Probando síntoma sudoracion fria excesiva"
    salience 5
    when
        $patient: Patient($id: id)
        $symptom: Symptom(patientId == $id, name == "Sudores frios", treated == false)
        $dLLC: Diagnosis(patientId == $id, type == LeucemiaType.LC)
        $dLLA: Diagnosis(patientId == $id, type == LeucemiaType.LA)
    then
        modify($symptom) {setTreated(true)};
        $dLLC.addSymptom($symptom);
        $dLLA.addSymptom($symptom);
end

rule "Probando síntoma dolor de huesos y articulaciones"
    salience 5
    when
        $patient: Patient($id: id)
        $symptom: Symptom(patientId == $id, name == "Dolor articulaciones/huesos", treated == false)
        $dLMA: Diagnosis(patientId == $id, type == LeucemiaType.MA)
        $dLLA: Diagnosis(patientId == $id, type == LeucemiaType.LA)
    then
        modify($symptom) {setTreated(true)};
        $dLMA.addSymptom($symptom);
        $dLLA.addSymptom($symptom);
end

rule "Probando síntoma presion bajo las costillas izquierdas inferiores"
    salience 5
    when
        $patient: Patient($id: id)
        $symptom: Symptom(patientId == $id, name == "Hepatoesplenomegalia", treated == false)
        $dLMC: Diagnosis(patientId == $id, type == LeucemiaType.MC)
        $dLLC: Diagnosis(patientId == $id, type == LeucemiaType.LC)
        $dLLA: Diagnosis(patientId == $id, type == LeucemiaType.LA)
    then
        modify($symptom) {setTreated(true)};
        $dLMC.addSymptom($symptom);
        $dLLC.addSymptom($symptom);
        $dLLA.addSymptom($symptom);
end

rule "Probando síntoma inflamación de ganglios linfáticos"
    salience 5
    when
        $patient: Patient($id: id)
        $symptom: Symptom(patientId == $id, name == "Inflamacion de ganglios linfaticos", treated == false)
        $dLLC: Diagnosis(patientId == $id, type == LeucemiaType.LC)
        $dLLA: Diagnosis(patientId == $id, type == LeucemiaType.LA)
    then
        modify($symptom) {setTreated(true)};
        $dLLC.addSymptom($symptom);
        $dLLA.addSymptom($symptom);
end

rule "Probando síntoma saciedad temprana o falta de apetito"
    salience 5
    when
        $patient: Patient($id: id)
        $symptom: Symptom(patientId == $id, name == "Saciedad temprana", treated == false)
        $dLLC: Diagnosis(patientId == $id, type == LeucemiaType.LC)
        $dLLA: Diagnosis(patientId == $id, type == LeucemiaType.LA)
    then
        modify($symptom) {setTreated(true)};
        $dLLC.addSymptom($symptom);
        $dLLA.addSymptom($symptom);
end

rule "Probando síntoma perdida de peso"
    salience 5
    when
        $patient: Patient($id: id)
        $symptom: Symptom(patientId == $id, name == "Perdida de peso", treated == false)
        $dLMA: Diagnosis(patientId == $id, type == LeucemiaType.MA)
        $dLLC: Diagnosis(patientId == $id, type == LeucemiaType.LC)
        $dLLA: Diagnosis(patientId == $id, type == LeucemiaType.LA)
    then
        modify($symptom) {setTreated(true)};
        $dLMA.addSymptom($symptom);
        $dLLC.addSymptom($symptom);
        $dLLA.addSymptom($symptom);
end

rule "Probando síntoma periodos mensatruales abundantes"
    salience 5
    when
        $patient: Patient($id: id)
        $symptom: Symptom(patientId == $id, name == "Menstruacion abundante", treated == false)
        $dLMA: Diagnosis(patientId == $id, type == LeucemiaType.MA)
        $dLLA: Diagnosis(patientId == $id, type == LeucemiaType.LA)
    then
        modify($symptom) {setTreated(true)};
        $dLMA.addSymptom($symptom);
        $dLLA.addSymptom($symptom);
end

rule "Probando síntoma hemorragia nasal"
    salience 5
    when
        $patient: Patient($id: id)
        $symptom: Symptom(patientId == $id, name == "Hemorragia nasal", treated == false)
        $dLMA: Diagnosis(patientId == $id, type == LeucemiaType.MA)
        $dLLA: Diagnosis(patientId == $id, type == LeucemiaType.LA)
    then
        modify($symptom) {setTreated(true)};
        $dLMA.addSymptom($symptom);
        $dLLA.addSymptom($symptom);
end

rule "Probando síntoma hemorragia/inflamación de las encías"
    salience 5
    when
        $patient: Patient($id: id)
        $symptom: Symptom(patientId == $id, name == "Hemorragia/inflamación de encías", treated == false)
        $dLMA: Diagnosis(patientId == $id, type == LeucemiaType.MA)
    then
        modify($symptom) {setTreated(true)};
        $dLMA.addSymptom($symptom);
end